"""Workspace-relative file authority shared by the openAdam Agent tools."""

from .anchored import (
    AnchoredDirectory,
    OpenInput,
    OutputDirectorySlot,
    OutputFileSlot,
    PublishOutcome,
    StagedFile,
    anchor_output_directory,
    anchor_output_file,
    anchor_root,
    create_staging,
    move_into,
    open_input_file,
    publish_directory,
    publish_file,
    read_child,
    remove_child,
    replace_child_atomically,
    write_child_exclusive,
)
from .core import (
    MAX_PATH_CHARS,
    ErrorFactory,
    FileAuthorityError,
    default_error,
    relative_parts,
)

__all__ = [
    "MAX_PATH_CHARS",
    "AnchoredDirectory",
    "ErrorFactory",
    "FileAuthorityError",
    "OpenInput",
    "OutputDirectorySlot",
    "OutputFileSlot",
    "PublishOutcome",
    "StagedFile",
    "anchor_output_directory",
    "anchor_output_file",
    "anchor_root",
    "create_staging",
    "default_error",
    "move_into",
    "open_input_file",
    "publish_directory",
    "publish_file",
    "read_child",
    "relative_parts",
    "remove_child",
    "replace_child_atomically",
    "write_child_exclusive",
]
